# Default values for all clusters that use this profile
is_prod_cluster: false

hosted_zone: example.com            # The domain to host your stuff under.

provisioner:
  state: s3://bucket.example.com
  kubernetes_version: 1.9.6
  ssh_public_key: "~/.ssh/example_rsa.pub"       # Path to the SSH key used to create the kops cluster when using kops
  api_loadbalancer_type: public     # More kops settings...
  dns: public
  authorization: RBAC
  networking: calico
  topology: public

  master-count: 1
  master-size: t2.medium
  node-count: 1
  node-size: t2.small

  specs:                              # The kops config will be downloaded and this
    cluster:                          # The kops config will be downloaded and this
      docker:                         # will be patched into the spec before
        logLevel: warn                # applying it to update the cluster config.
        logOpt:                       # This allows kops clusters to be fully
        - max-size=10m                # customised and updated automatically.
        - max-file=5
        logDriver: json-file
        ipMasq: true
        ipTables: true
      fileAssets:
      - content: |
          apiVersion: audit.k8s.io/v1beta1
          kind: Policy
          rules:
          - level: Metadata
        name: audit-policy.yaml
        roles:
        - Master
    instanceGroups:
      nodes:                    # name of the IG
        nodeLabels:
          kops.k8s.io/test: test-label
        cloudLabels:
          project: test-project-label
