# region: eu-west-1         # todo - the aws provider should populate this automatically

# kube_context: "{{ cluster }}.{{ region }}.{{ account_name }}.{{ domain }}"    # populated by default but overrideable

#s3:
#  kms_key: "arn:..."        # added to generated files to support e.g. encrypted terraform S3 backends.
                             # todo - how to pull this out of the pre-init kapp which should create it?

provisioner:
  # from https://stable.release.core-os.net/amd64-usr/current/coreos_production_ami_hvm_eu-west-1.txt
  node_image_id: ami-1d3cd8f0

  master:
    zones:
    - eu-west-1a
    worker:
      zones:
      - eu-west-1a
      - eu-west-1b
      - eu-west-1c
